//
//  JRC.h
//
//  Copyright 2016 Go Travel Un Limited
//  This code is distributed under the terms and conditions of the MIT license.
//

#import <Foundation/Foundation.h>

@interface JRC : NSObject

+ (UIColor *)CLEAR_COLOR;
+ (UIColor *)BLACK_COLOR;
+ (UIColor *)WHITE_COLOR;

+ (UIColor *)AIRLINES_AIRLINE_IATA;

+ (UIColor *)AIRPORT_PICKER_AIRPORT_CITY_LABEL_TEXT_COLOR;
+ (UIColor *)AIRPORT_PICKER_AIRPORT_COUNTRY_TEXT_COLOR;
+ (UIColor *)AIRPORT_PICKER_AIRPORT_IATA_LABEL_COLOR;
+ (UIColor *)AIRPORT_PICKER_AIRPORT_IATA_LABEL_COLOR_ANY;

+ (UIColor *)ALERT_BORDER;
+ (UIColor *)ALERT_BUTTON;
+ (UIColor *)ALERT_MESSAGE;

+ (UIColor *)BAR_DARK_BOTTOM_BORDER;
+ (UIColor *)BAR_LIGHT_BOTTOM_BORDER;

+ (UIColor *)CELL_SWIPE_DELETE_BG;

+ (UIColor *)COMMON_BACKGROUND;
+ (UIColor *)COMMON_BLACK_POPOVER_TINT;
+ (UIColor *)COMMON_CELL_SELECTED_BACKGROUND_COLOR;
+ (UIColor *)COMMON_CELL_SELECTED_BACKGROUND_COLOR_OPAQUE;
+ (UIColor *)COMMON_HELPER_VIEW_BG_COLOR;
+ (UIColor *)COMMON_HIGHLIGHTED_TEXT;
+ (UIColor *)COMMON_HINT_POPOVER_BLUR_TINT;
+ (UIColor *)COMMON_HYPERLINK_TEXT;
+ (UIColor *)COMMON_LIGHT_TEXT;
+ (UIColor *)COMMON_ORANGE_COLOR;
+ (UIColor *)COMMON_POPOVER_BACKGROUND;
+ (UIColor *)COMMON_POPUP_BACKGROUND_COLOR;
+ (UIColor *)COMMON_POPUP_TITLE_COLOR;
+ (UIColor *)COMMON_SEARCHBAR_BOTTOM_BORDER;
+ (UIColor *)COMMON_SEARCHBAR_TOP_BORDER;
+ (UIColor *)COMMON_TABLECELL_SEPARATOR;
+ (UIColor *)COMMON_TABLE_HEADER_TEXT;
+ (UIColor *)COMMON_TEXT;
+ (UIColor *)COMMON_UNACTIVE_TEXT;

+ (UIColor *)DATE_PICKER_NORMAL_DATE_COLOR;
+ (UIColor *)DATE_PICKER_NORMAL_SELECTED_DATE_COLOR;
+ (UIColor *)DATE_PICKER_TODAY_LABEL_COLOR;

+ (UIColor *)DELETE_BUTTON_DISABLED_TITLE;
+ (UIColor *)DELETE_BUTTON_TITLE;

+ (UIColor *)FAVOURITES_HEADER_TEXT_COLOR;

+ (UIColor *)FEEDBACK_BUTTONS;

+ (UIColor *)FILTER_SECTION_HEADER_TITLE;
+ (UIColor *)FILTER_CELL_TITLE;

+ (UIColor *)FILTER_DISABLED_LABEL_TEXT;
+ (UIColor *)FILTER_LABEL_TEXT;
+ (UIColor *)FILTER_PRICE_TOOLBAR_LINE;
+ (UIColor *)FILTER_RESET_BUTTON_TEXT_COLOR_IPAD;

+ (UIColor *)SECOND_THEME_COLOR;

+ (UIColor *)INFORMATION_TABLE_CELL_TITLE_COLOR;
+ (UIColor *)INFORMATION_FAQ_CELL_SEPARATOR;

+ (UIColor *)MAGIC_FARE_COLOR;
+ (UIColor *)MAIN_SCREEN_BACKGROUND_COLOR;

+ (UIColor *)MAP_ANY_SEASON_PLACEHOLDER;
+ (UIColor *)MAP_CALLOUT_SEPARATOR;
+ (UIColor *)MAP_CALLOUT_TEXT;
+ (UIColor *)MAP_COUNT_TEXT;
+ (UIColor *)MAP_LABEL_BG;
+ (UIColor *)MAP_MULTIPLE_CALLOUT_CITY;
+ (UIColor *)MAP_NAVIGATION_BAR;
+ (UIColor *)MAP_ORIGIN_LABEL_BG;
+ (UIColor *)MAP_SC_NORMAL_TITLE_COLOR;
+ (UIColor *)MAP_SC_NORMAL_TITLE_COLOR_IPAD;
+ (UIColor *)MAP_SC_SELECTED_TITLE_COLOR;
+ (UIColor *)MAP_SC_SELECTED_TITLE_COLOR_IPAD;
+ (UIColor *)MAP_SC_STROKE;
+ (UIColor *)MAP_SC_STROKE_IPAD;
+ (UIColor *)MAP_UNACTUAL_LABEL_BG;

+ (UIColor *)MENU_BACKGROUND_COLOR;
+ (UIColor *)MENU_ITEM_IMAGE_TINT_COLOR;
+ (UIColor *)MENU_ITEM_LABEL_HIGHLIGHTED_TEXT_COLOR;
+ (UIColor *)MENU_ITEM_LABEL_TEXT_COLOR;
+ (UIColor *)MENU_SEPARATOR_COLOR;

+ (UIColor *)NAVIGATION_BAR_BACKGROUND_COLOR;

+ (UIColor *)PASSENGERS_EMPTY_PLACEHOLDER;
+ (UIColor *)PASSENGERS_FORM_SEPARATOR;
+ (UIColor *)PASSENGERS_FORM_SUBTITLE;
+ (UIColor *)PASSENGERS_FORM_WRONG_FIELD;
+ (UIColor *)PASSENGERS_LIST_DOCUMENT_TYPE;
+ (UIColor *)PASSENGER_OCR_HELP_HINT_BG;
+ (UIColor *)PASSENGER_LIST_CELL_MALE_BG;
+ (UIColor *)PASSENGER_LIST_CELL_FEMALE_BG;

+ (UIColor *)PRICE_CALENDAR_CHART_BORDER;
+ (UIColor *)PRICE_CALENDAR_DAY;
+ (UIColor *)PRICE_CALENDAR_MINIMAL_PRICE_LABEL;
+ (UIColor *)PRICE_CALENDAR_POINTS;
+ (UIColor *)PRICE_CALENDAR_PRICE;
+ (UIColor *)PRICE_CALENDAR_PRICE_IPAD;
+ (UIColor *)PRICE_CALENDAR_SWITCHER;
+ (UIColor *)PRICE_CALENDAR_WEEKDAY;
+ (UIColor *)PRICE_CALENDAR_SELECTED_VIEW_PATTERN;

+ (UIColor *)SCENE_SHADOW_COLOR;

+ (UIColor *)SEARCH_BAR_CANCEL_HI_TITLE_COLOR;
+ (UIColor *)SEARCH_BAR_CANCEL_TITLE_COLOR;
+ (UIColor *)SEARCH_RESULTS_BEST_CHEAP;
+ (UIColor *)SEARCH_RESULTS_BEST_COMFORT;
+ (UIColor *)SEARCH_RESULTS_BEST_QUICK;
+ (UIColor *)SEARCH_RESULTS_MAGIC_FARE_PRICE_COLOR;
+ (UIColor *)SEARCH_RESULTS_MAGIC_FARE_STRIKE_THROUGH_COLOR;
+ (UIColor *)SEARCH_RESULTS_PRICE_DELTA_NEGATIVE_COLOR;
+ (UIColor *)SEARCH_RESULTS_PRICE_DELTA_POSITIVE_COLOR;
+ (UIColor *)SEARCH_RESULTS_PRICE_LABEL_COLOR;
+ (UIColor *)SEARCH_RESULTS_PRICE_LABEL_DIS;
+ (UIColor *)SEARCH_RESULTS_PROGRESS_BAR_COLOR;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_LIGHT_MONOCHROME;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_LIGHT_NORMAL;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_LIGHT_NORMAL_IPAD;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_MONOCHROME;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_NORMAL;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_NORMAL_IPAD;
+ (UIColor *)SEARCH_RESULTS_SEGMENT_TRANSFERS_LABEL_NORMAL;
+ (UIColor *)SEARCH_RESULT_OFFER_AIRPORT_COLOR;
+ (UIColor *)SEARCH_RESULT_OFFER_TEXT_COLOR;
+ (UIColor *)SEARCH_RESULT_SC_SEGMENT_NORMAL_TITLE;
+ (UIColor *)SEARCH_RESULT_SC_SEGMENT_RIBBON;
+ (UIColor *)SEARCH_RESULT_SC_SEGMENT_STROKE;
+ (UIColor *)SEARCH_RESULT_SC_SEGMENT_TITLE;
+ (UIColor *)SEARCH_RESULT_SC_STROKE;
+ (UIColor *)SEARCH_RESULT_TICKET_DATE_COLOR;
+ (UIColor *)SEARCH_RESULT_TICKET_DOTS_COLOR;
+ (UIColor *)SEARCH_RESULTS_FULL_PRICE_LABEL;

+ (UIColor *)SORT_CHECK_BOX_COLOR;

+ (UIColor *)SF_AIRPORT_CELL_PLACEHOLDER_COLOR;
+ (UIColor *)SF_AIRPORT_CITY_LABEL_TEXT_COLOR;
+ (UIColor *)SF_AIRPORT_COUNTRY_TEXT_COLOR;
+ (UIColor *)SF_AIRPORT_IATA_LABEL_TEXT_COLOR;

+ (UIColor *)SF_CELL_IMAGES_TINT;

+ (UIColor *)SF_DATES_BACKGROUND_TINT;
+ (UIColor *)SF_DATES_TEXT_COLOR;;

+ (UIColor *)SF_BACKGROUND_COLOR;

+ (UIColor *)SF_CELL_HIGHLIGHTED_COLOR;

+ (UIColor *)SF_DATE_CELL_LABEL_TEXT_COLOR;

+ (UIColor *)SF_PASSENGERS_COUNT_ACTIVE;
+ (UIColor *)SF_PASSENGERS_BG;

+ (UIColor *)SF_SEGMENTED_CONTROL_BACKGROUND_COLOR;
+ (UIColor *)SF_SEGMENTED_CONTROL_SEGMENT_RIBBON;
+ (UIColor *)SF_SEGMENTED_CONTROL_SEGMENT_TITLE_IPAD;
+ (UIColor *)SF_SEGMENTED_CONTROL_SEGMENT_TITLE_IPHONE;
+ (UIColor *)SF_SEGMENTED_CONTROL_SEGMENT_TITLE_TINT;

+ (UIColor *)SF_VOICE_SEARCH_ELLIPSE_BORDER;

+ (UIColor *)SUBSCRIPTIONS_DELETE_BUTTON_TITLE;
+ (UIColor *)SUBSCRIPTIONS_DELTA_PRICE_DOWN;
+ (UIColor *)SUBSCRIPTIONS_DELTA_PRICE_UP;
+ (UIColor *)SUBSCRIPTIONS_FLEX_SEARCH_NOTE;
+ (UIColor *)SUBSCRIPTIONS_PLACEHOLDER_DISABLED_PUSH_TEXT;
+ (UIColor *)SUBSCRIPTIONS_PLACEHOLDER_TEXT;
+ (UIColor *)SUBSCRIPTIONS_PRICE;
+ (UIColor *)SUBSCRIPTIONS_PASSENGERS_IMG;

+ (UIColor *)THEME_COLOR;

+ (UIColor *)TICKET_FLIGHT_SEGMENT_HEADER_AIRPLANE_IMAGE;
+ (UIColor *)TICKET_FLIGHT_STATS_BUTTON;
+ (UIColor *)TICKET_FLIGHT_STATS_COMMON_COLOR;
+ (UIColor *)TICKET_FLIGHT_STATS_DELAY_COLOR;
+ (UIColor *)TICKET_FLIGHT_STATS_ON_TIME_COLOR;

+ (UIColor *)TICKET_HEADER_BACKGROUND_COLOR;

+ (UIColor *)TICKET_MAGIC_FARE_PRICE_COLOR;

+ (UIColor *)TICKET_ACTIVE_GATE_NAME_COLOR;
+ (UIColor *)TICKET_INACTIVE_PRICE_COLOR;


+ (UIColor *)TICKET_PRICES_CELL_SEL_BG;
+ (UIColor *)TICKET_PRICES_POPOVER_BLUR;

+ (UIColor *)WAITING_ANNOTATION_TEXT_COLOR;
+ (UIColor *)WAITING_BACKGROUND;
+ (UIColor *)WAITING_BAR_COLOR_IPAD;
+ (UIColor *)WAITING_BAR_COLOR_IPHONE;
+ (UIColor *)WAITING_DOTS_COLOR;
+ (UIColor *)WAITING_TOP_PROGRESS_BAR_LINE_COLOR;

+ (UIColor *)WHITE_NAVIGATION_BAR_COMMON_BORDER_COLOR;
+ (UIColor *)WHITE_NAVIGATION_BAR_COMMON_CONTENT_COLOR;

+ (UIColor *)HISTORY_DATES_COLOR;

+ (UIColor *)WIDGET_BUTTON_BACKGROUND_COLOR;
+ (UIColor *)WIDGET_TEXT;
+ (UIColor *)WIDGET_TEXT_BUTTON;

+ (UIColor *)BROWSER_NAV_BUTTON_TEXT_NORMAL;
+ (UIColor *)BROWSER_NAV_BUTTON_TEXT_DISABLED;

+ (UIColor *)COMPACT_SF_HIGHLIGHTED_CELL;
+ (UIColor *)COMPACT_SF_TEXT;
+ (UIColor *)COMPACT_SF_FOOTER_LINE;
+ (UIColor *)COMPACT_SF_CHECKBOX;

+ (UIColor *)WATCH_DELTA_UP_COLOR;
+ (UIColor *)WATCH_DELTA_DOWN_COLOR;

+ (UIColor *)JR_OFFER_AS_CLOSE_BUTTON_COLOR;

@end
